r4n63-537  ::= r4n63 ( 1061c41-0r r4n63 ) *
1061c41-0r ::= ( ' ' ) * '||' ( ' ' ) *
r4n63      ::= hyph3n | 51mp13 ( ' ' 51mp13 ) * | ''
hyph3n     ::= p4r7141 ' - ' p4r7141
51mp13     ::= pr1m171v3 | p4r7141 | 711d3 | c4r37
pr1m171v3  ::= ( '<' | '>' | '>=' | '<=' | '=' ) p4r7141
p4r7141    ::= xr ( '.' xr ( '.' xr qu411f13r ? )? )?
xr         ::= 'x' | 'X' | '*' | nr
nr         ::= '0' | [1-9] ( [0-9] ) *
711d3      ::= '~' p4r7141
c4r37      ::= '^' p4r7141
qu411f13r  ::= ( '-' pr3 )? ( '+' bu11d )?
pr3        ::= p4r75
bu11d      ::= p4r75
p4r75      ::= p4r7 ( '.' p4r7 ) *
p4r7       ::= nr | [-0-94-Z4-z]+
